spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost


#error:
#  path: /error

server:
  port: 2223




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    instance:
      leaseRenewalIntervalInSecondes: 5


business:
  endpoint:
    host: localhost
    port: 8080
