spring:
  application:
    name: user-service
  data:
    mongodb:
      host: 192.168.20.9


#error:
#  path: /error

server:
  port: 2223




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    instance:
      leaseRenewalIntervalInSecondes: 5