package com.kyle.microservices.service.userLogin;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-10T00:19:50.124+12:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "userLogin", 
                  wsdlLocation = "file:/C:/work/workspace/IdeaProjects/microservice-user/src/main/resources/wsdl/userLogin.wsdl",
                  targetNamespace = "http://ofbiz.apache.org/service/") 
public class UserLogin extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ofbiz.apache.org/service/", "userLogin");
    public final static QName UserLoginPort = new QName("http://ofbiz.apache.org/service/", "userLoginPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/work/workspace/IdeaProjects/microservice-user/src/main/resources/wsdl/userLogin.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/work/workspace/IdeaProjects/microservice-user/src/main/resources/wsdl/userLogin.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserLogin(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserLogin(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserLogin() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public UserLogin(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserLogin(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserLogin(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns UserLoginPortType
     */
    @WebEndpoint(name = "userLoginPort")
    public UserLoginPortType getUserLoginPort() {
        return super.getPort(UserLoginPort, UserLoginPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserLoginPortType
     */
    @WebEndpoint(name = "userLoginPort")
    public UserLoginPortType getUserLoginPort(WebServiceFeature... features) {
        return super.getPort(UserLoginPort, UserLoginPortType.class, features);
    }

}
