package com.kyle.microservices.service.userLogin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-10T00:19:50.113+12:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://ofbiz.apache.org/service/", name = "userLoginPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface UserLoginPortType {

    @WebMethod(action = "http://localhost:8080/webtools/control/SOAPService")
    @WebResult(name = "map-HashMap", targetNamespace = "http://ofbiz.apache.org/service/", partName = "map-HashMap")
    public MapMap userLogin(
            @WebParam(partName = "map-Map", name = "map-Map")
                    MapMap mapMap
    );
}
