
package com.kyle.microservices.service.userLogin;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-10T00:19:50.062+12:00
 * Generated source version: 3.1.11
 */
public final class UserLoginPortType_UserLoginPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ofbiz.apache.org/service/", "userLogin");

    private UserLoginPortType_UserLoginPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = UserLogin.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        UserLogin ss = new UserLogin(wsdlURL, SERVICE_NAME);
        UserLoginPortType port = ss.getUserLoginPort();

        {
            System.out.println("Invoking userLogin...");
            MapEntry mapEntryU = new MapEntry();
            MapEntry mapEntryP = new MapEntry();

            MapKey mapKeyU = new MapKey();
            StdString stdStringKU = new StdString();
            stdStringKU.setValue("login.username");
            mapKeyU.setStdString(stdStringKU);
            MapValue mapValueU = new MapValue();
            StdString stdStringVU = new StdString();
            stdStringVU.setValue("admin");
            mapValueU.setStdString(stdStringVU);

            MapKey mapKeyP = new MapKey();
            StdString stdStringKP = new StdString();
            stdStringKP.setValue("login.password");
            mapKeyP.setStdString(stdStringKP);
            MapValue mapValueP = new MapValue();
            StdString stdStringVP = new StdString();
            stdStringVP.setValue("ofbiz");
            mapValueP.setStdString(stdStringVP);

            mapEntryU.setMapKey(mapKeyU);
            mapEntryU.setMapValue(mapValueU);
            mapEntryP.setMapKey(mapKeyP);
            mapEntryP.setMapValue(mapValueP);

            List<MapEntry> mapEntries = new ArrayList<>();
            mapEntries.add(mapEntryU);
            mapEntries.add(mapEntryP);

            MapMap _userLogin_mapMap = new MapMap();
            _userLogin_mapMap.mapEntry = mapEntries;
            MapMap _userLogin__return = port.userLogin(_userLogin_mapMap);
            System.out.println("userLogin.result=" + _userLogin__return);


        }

        System.exit(0);
    }

}
